//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harrods.Service.Employees.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeEntity", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    public partial class EmployeeEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FNameField;
        
        private string GenderField;
        
        private int IDField;
        
        private string LNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName
        {
            get
            {
                return this.FNameField;
            }
            set
            {
                this.FNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName
        {
            get
            {
                return this.LNameField;
            }
            set
            {
                this.LNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressEntity", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    public partial class AddressEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AddressIDField;
        
        private string CityField;
        
        private string CountryField;
        
        private string EmailField;
        
        private int EmployeeIDField;
        
        private string Line1Field;
        
        private string Line2Field;
        
        private string POBoxField;
        
        private string PhoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID
        {
            get
            {
                return this.AddressIDField;
            }
            set
            {
                this.AddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                this.EmployeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1
        {
            get
            {
                return this.Line1Field;
            }
            set
            {
                this.Line1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2
        {
            get
            {
                return this.Line2Field;
            }
            set
            {
                this.Line2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBox
        {
            get
            {
                return this.POBoxField;
            }
            set
            {
                this.POBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    public partial class ExceptionFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BaseExceptionField;
        
        private string DescriptionField;
        
        private string MessageField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseException
        {
            get
            {
                return this.BaseExceptionField;
            }
            set
            {
                this.BaseExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEmployeeContract")]
public interface IEmployeeContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/CreateEmployeeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/CreateEmployeeExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    bool CreateEmployee(Harrods.Service.Employees.Entities.EmployeeEntity Employee, Harrods.Service.Employees.Entities.AddressEntity address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/CreateEmployeeResponse")]
    System.Threading.Tasks.Task<bool> CreateEmployeeAsync(Harrods.Service.Employees.Entities.EmployeeEntity Employee, Harrods.Service.Employees.Entities.AddressEntity address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/UpdateEmployeeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/UpdateEmployeeExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    bool UpdateEmployee(Harrods.Service.Employees.Entities.EmployeeEntity Employee);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/UpdateEmployeeResponse")]
    System.Threading.Tasks.Task<bool> UpdateEmployeeAsync(Harrods.Service.Employees.Entities.EmployeeEntity Employee);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/DeleteEmployeeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/DeleteEmployeeExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    bool DeleteEmployee(Harrods.Service.Employees.Entities.EmployeeEntity EmployeeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/DeleteEmployeeResponse")]
    System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(Harrods.Service.Employees.Entities.EmployeeEntity EmployeeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/GetEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/GetEmployeeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/GetEmployeeExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    Harrods.Service.Employees.Entities.EmployeeEntity GetEmployee(int EmployeeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/GetEmployee", ReplyAction="http://tempuri.org/IEmployeeContract/GetEmployeeResponse")]
    System.Threading.Tasks.Task<Harrods.Service.Employees.Entities.EmployeeEntity> GetEmployeeAsync(int EmployeeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/GetAllEmployees", ReplyAction="http://tempuri.org/IEmployeeContract/GetAllEmployeesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/GetAllEmployeesExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    Harrods.Service.Employees.Entities.EmployeeEntity[] GetAllEmployees();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/GetAllEmployees", ReplyAction="http://tempuri.org/IEmployeeContract/GetAllEmployeesResponse")]
    System.Threading.Tasks.Task<Harrods.Service.Employees.Entities.EmployeeEntity[]> GetAllEmployeesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/UpdateAddress", ReplyAction="http://tempuri.org/IEmployeeContract/UpdateAddressResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/UpdateAddressExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    bool UpdateAddress(Harrods.Service.Employees.Entities.AddressEntity Address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/UpdateAddress", ReplyAction="http://tempuri.org/IEmployeeContract/UpdateAddressResponse")]
    System.Threading.Tasks.Task<bool> UpdateAddressAsync(Harrods.Service.Employees.Entities.AddressEntity Address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/DeleteAddress", ReplyAction="http://tempuri.org/IEmployeeContract/DeleteAddressResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/DeleteAddressExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    bool DeleteAddress(Harrods.Service.Employees.Entities.AddressEntity Address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/DeleteAddress", ReplyAction="http://tempuri.org/IEmployeeContract/DeleteAddressResponse")]
    System.Threading.Tasks.Task<bool> DeleteAddressAsync(Harrods.Service.Employees.Entities.AddressEntity Address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/GetAddress", ReplyAction="http://tempuri.org/IEmployeeContract/GetAddressResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Harrods.Service.Employees.Entities.ExceptionFaultContract), Action="http://tempuri.org/IEmployeeContract/GetAddressExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Harrods.Service.Employees.Entities")]
    Harrods.Service.Employees.Entities.AddressEntity GetAddress(int AddressID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeContract/GetAddress", ReplyAction="http://tempuri.org/IEmployeeContract/GetAddressResponse")]
    System.Threading.Tasks.Task<Harrods.Service.Employees.Entities.AddressEntity> GetAddressAsync(int AddressID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEmployeeContractChannel : IEmployeeContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EmployeeContractClient : System.ServiceModel.ClientBase<IEmployeeContract>, IEmployeeContract
{
    
    public EmployeeContractClient()
    {
    }
    
    public EmployeeContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EmployeeContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmployeeContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmployeeContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool CreateEmployee(Harrods.Service.Employees.Entities.EmployeeEntity Employee, Harrods.Service.Employees.Entities.AddressEntity address)
    {
        return base.Channel.CreateEmployee(Employee, address);
    }
    
    public System.Threading.Tasks.Task<bool> CreateEmployeeAsync(Harrods.Service.Employees.Entities.EmployeeEntity Employee, Harrods.Service.Employees.Entities.AddressEntity address)
    {
        return base.Channel.CreateEmployeeAsync(Employee, address);
    }
    
    public bool UpdateEmployee(Harrods.Service.Employees.Entities.EmployeeEntity Employee)
    {
        return base.Channel.UpdateEmployee(Employee);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateEmployeeAsync(Harrods.Service.Employees.Entities.EmployeeEntity Employee)
    {
        return base.Channel.UpdateEmployeeAsync(Employee);
    }
    
    public bool DeleteEmployee(Harrods.Service.Employees.Entities.EmployeeEntity EmployeeID)
    {
        return base.Channel.DeleteEmployee(EmployeeID);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(Harrods.Service.Employees.Entities.EmployeeEntity EmployeeID)
    {
        return base.Channel.DeleteEmployeeAsync(EmployeeID);
    }
    
    public Harrods.Service.Employees.Entities.EmployeeEntity GetEmployee(int EmployeeID)
    {
        return base.Channel.GetEmployee(EmployeeID);
    }
    
    public System.Threading.Tasks.Task<Harrods.Service.Employees.Entities.EmployeeEntity> GetEmployeeAsync(int EmployeeID)
    {
        return base.Channel.GetEmployeeAsync(EmployeeID);
    }
    
    public Harrods.Service.Employees.Entities.EmployeeEntity[] GetAllEmployees()
    {
        return base.Channel.GetAllEmployees();
    }
    
    public System.Threading.Tasks.Task<Harrods.Service.Employees.Entities.EmployeeEntity[]> GetAllEmployeesAsync()
    {
        return base.Channel.GetAllEmployeesAsync();
    }
    
    public bool UpdateAddress(Harrods.Service.Employees.Entities.AddressEntity Address)
    {
        return base.Channel.UpdateAddress(Address);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateAddressAsync(Harrods.Service.Employees.Entities.AddressEntity Address)
    {
        return base.Channel.UpdateAddressAsync(Address);
    }
    
    public bool DeleteAddress(Harrods.Service.Employees.Entities.AddressEntity Address)
    {
        return base.Channel.DeleteAddress(Address);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteAddressAsync(Harrods.Service.Employees.Entities.AddressEntity Address)
    {
        return base.Channel.DeleteAddressAsync(Address);
    }
    
    public Harrods.Service.Employees.Entities.AddressEntity GetAddress(int AddressID)
    {
        return base.Channel.GetAddress(AddressID);
    }
    
    public System.Threading.Tasks.Task<Harrods.Service.Employees.Entities.AddressEntity> GetAddressAsync(int AddressID)
    {
        return base.Channel.GetAddressAsync(AddressID);
    }
}
